### ISSUE TITLE
Error during loading IC file in SEMSIM calculation

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/monarch-semantic-similarity-profiles#21]
## The issue:

During the SEMSIM calculation, a warning message is displayed `Failed to import custom IC map: Error parsing IC value: invalid float literal`. The SEMSIM file is generated without any errors.
However, this warning showing the impossibility of loading the IC file might be affecting the SEMSIM values.
I verified all values in the information content column to ensure they are numeric, and indeed they are.

## Header of IC file:

```
id      information_content
HP:0000001      4.096300700299448
HP:0000002      13.062826751687464
HP:0000003      18.192109768632434
HP:0000005      12.834557764014347
HP:0000006      18.192109768632434
HP:0000007      18.192109768632434
HP:0000008      11.237913458245558
HP:0000009      13.384754846574829
HP:0000010      16.607147267911277
```

## Command executed:

```sh
runoak --stacktrace -vvv  -i semsimian:sqlite:data/ontology/phenio-monarch.db similarity -p i \
--set1-file data/tmp/hp_terms.txt \
--set2-file data/tmp/hp_terms.txt \
--min-jaccard-similarity 0.4 \
--information-content-file  data/tmp/phenio_monarch_hp_ic.tsv \
-O csv \
-o profiles/phenio-monarch-hp-hp.0.4.semsimian.tsv
```

## Warning Message:

`Failed to import custom IC map: Error parsing IC value: invalid float literal`

## Library Versions:

oaklib                    0.6.14
semsimian                 0.2.17

**Comment by souzadevinicius** [comment]
[phenio_monarch_hp_ic.zip](https://github.com/user-attachments/files/16468656/phenio_monarch_hp_ic.zip)
IC File

**Comment by matentzn** [comment]
@hrshdhgd can you check that?

the steps

1. Produce IC table with oak
2. Reading it with semsimian

should be seamless!

**Comment by caufieldjh** [comment]
Good catch, and thanks to @hrshdhgd for https://github.com/monarch-initiative/semsimian/pull/132

**Comment by souzadevinicius** [comment]
Fixed! Thank you, @hrshdhgd
